name: Template Validation

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  validate-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate TypeScript
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx,.js,.jsx

      - name: Check for template files
        run: |
          if [ ! -f ".env.example" ]; then
            echo "❌ .env.example file is missing"
            exit 1
          fi
          if [ ! -f "TEMPLATE_README.md" ]; then
            echo "❌ TEMPLATE_README.md file is missing"
            exit 1
          fi
          if [ ! -f "TEMPLATE_CHECKLIST.md" ]; then
            echo "❌ TEMPLATE_CHECKLIST.md file is missing"
            exit 1
          fi
          if [ ! -f "setup-template.sh" ]; then
            echo "❌ setup-template.sh file is missing"
            exit 1
          fi
          echo "✅ All template files are present"

      - name: Validate Firebase config structure
        run: |
          if ! grep -q "EXPO_PUBLIC_FIREBASE_API_KEY" .env.example; then
            echo "❌ Firebase configuration template is incomplete"
            exit 1
          fi
          echo "✅ Firebase configuration template is valid"

      - name: Validate translation files
        run: |
          if [ ! -f "locales/en.json" ]; then
            echo "❌ English translation file is missing"
            exit 1
          fi
          if [ ! -f "locales/es.json" ]; then
            echo "❌ Spanish translation file is missing"
            exit 1
          fi
          # Validate JSON syntax
          node -e "
            const en = require('./locales/en.json');
            const es = require('./locales/es.json');
            console.log('✅ Translation files are valid JSON');
          "

      - name: Test Expo configuration
        run: |
          # Check if app.json has required fields
          node -e "
            const config = require('./app.json');
            if (!config.expo.name || !config.expo.slug) {
              console.error('❌ app.json is missing required fields');
              process.exit(1);
            }
            console.log('✅ Expo configuration is valid');
          "
